version: 2
defaults: &defaults
  working_directory: ~/my-app-front
  docker:
    - image: circleci/node:10.16.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-front
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm run build
      - persist_to_workspace:
         root: . # Persist current working directory
         paths: ./* # Glob. Will persist everything in folder
      - store_artifacts:
          path: ./build # executable
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-front
      - run: npm install && npm run test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
         at: ~/my-app-front
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm run build
      - add_ssh_keys:
         fingerprints:
           - "8c:85:b7:6b:88:eb:40:40:e9:0f:b7:49:dd:58:35:a4"
      - run:
         name: Clone backend
         command: >-
           GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
           git clone git@github.com:AlexeyBondar1992/smart-api.git ~/my-app-front/my-app-back
      - run:
         name: Move build to backend repository
         command:
           ls &&
           mv ~/my-app-front/build ~/my-app-front/my-app-back &&
           cd ~/my-app-front/my-app-back &&
           git add ~/my-app-front/my-app-back/build
      - run:
         name: Deploy front
         command: >-
           GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
           git commit -m "build" &&
           git push
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test