version: 2
defaults: &defaults
  working_directory: home/circleci/my-app-front
  docker:
    - image: circleci/node:10.16.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install && npm test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install && npm build
      - attach_workspace:
         at: home/circleci/my-app-front
      - add_ssh_keys:
         fingerprints:
           - "31:b0:29:dd:4a:62:52:30:75:54:4f:ca:70:fe:fe:1c"
      - run:
         name: Clone backend
         command: >-
           GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
           git clone git@github.com:AlexeyBondar1992/smart-api.git home/circleci/my-app-front/my-app-back
      - run:
         name: Move build to backend repository
         command:
           mv home/circleci/my-app-front/build home/circleci/my-app-front/my-app-back &&
           cd home/circleci/my-app-front/my-app-back &&
           git add home/circleci/my-app-front/my-app-back/build
      - run:
         name: Deploy front
         command: >-
           GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
           git commit -m "build" &&
           git push
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test