version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install && npm test && npm build
      - run:
          shell: /bin/bash
          command: |
            mkdir -p /fullApp
            cd /fullApp
            git clone https://github.com/AlexeyBondar1992/smart-api
            mv /build /fullApp
            git add /fullApp/build
            git commit --message=build
            git push
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build