version: 2
defaults: &defaults
  working_directory: ~/my-app-front
  docker:
    - image: circleci/node:10.16.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-front
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm run build
      - persist_to_workspace:
         root: . # Persist current working directory
         paths: ./* # Glob. Will persist everything in folder
      - store_artifacts:
          path: ./build # executable
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/my-app-front
      - run: npm run test
  triger_backend_build:
    docker:
      - image: spotify/alpine
    steps:
      - run:
         name: Trigger the Build Job
         command: |
           printf "Triggering an $PROJECT build on the $CIRCLE_BRANCH branch\n\n"
           BUILD_INFO=$(curl -X POST -H -d \
               "{}" \
               "https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT/tree/$CIRCLE_BRANCH?circle-token=$CIRCLE_TOKEN")
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - triger_backend_build:
          requires:
            - test