version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
         name: install-npm
         command: npm install
      - run:
         name: build
         command: npm build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: npm install && npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test:
      #    requires:
      #      - build